name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: format('{{Thank you {0} for opening your first pull request in our repository, one of our maintainers will get in touch with you soon.}}', github.author)
        pr-message: format('{{Thank you {0} for opening your first pull request in our repository, one of our maintainers will get in touch with you soon.}}', github.author)