name: Test
on:
  issue_comment:
    created:
      patterns:
        - '/test @(.*)'
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: 'Send message'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello, @{{ github.event.issue_comment.user.login }}!'
